apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blog
  annotations:
      kubernetes.io/ingress.global-static-ip-name: blog-gke
      ingress.gcp.kubernetes.io/pre-shared-cert: threetreeslight-com
spec:
  backend:
    serviceName: blog
    servicePort: 8080
