baseURL = "https://threetreeslight.com"
languageCode = "ja-JP"
title = "iii threetreeslight"

# https://themes.gohugo.io/hemingway2/
theme = "hemingway2"

description = "This is threetreeslight."
keywords = ["startup,programming"]

pygmentsUseClasses = true
pygmentsCodeFences = true

enableEmoji = true

[taxonomies]
tag = "tags"
category = "categories"

[params]

[params.highlight]
style = "github"

[[params.social]]
url = "https://github.com/threetreeslight"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/threetreeslight"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://www.linkedin.com/in/akiramiki"
fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

[permalinks]
  posts = "posts/:year/:month/:day/:title"
