version: "3"
services:
  site:
    image: threetreeslight/docker-hugo
    volumes:
      - ./blog:/site
    ports:
      - 1313:1313
    command: ["hugo", "server", "-D", "--bind=0.0.0.0"]

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEBUG: 1
    ports:
      - 8888:8080

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - default
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus-local.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
      - prometheus-data:/prometheus
    depends_on:
      - alertmanager
      - blackbox-exporter
      - cadvisor
      - node-exporter
    networks:
      - default
    ports:
      - 9090:9090

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    networks:
      - default
    ports:
      - 9115:9115

  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - console
    networks:
      - default
    ports:
      - 8080:8080

  node-exporter:
    image: quay.io/prometheus/node-exporter
    networks:
      - default
    pid: "host"
    ports:
      - 9100:9100

  fluentd-gcp:
    build:
      context: ./fluentd-gcp
      dockerfile: Dockerfile
    volumes:
      - ./fluentd-gcp/config:/etc/fluent/config.d
    ports:
      - 24224:24224

volumes:
  prometheus-data:
    driver: local
  grafana-storage:
    driver: local
