version: "3"
services:
  site:
    build:
      context: .
    volumes:
      - .:/site
    ports:
      - "1313:1313"
    command: ["hugo", "server", "--baseURL=http://${DOCKER_HOST_IP}:1313", "--bind=0.0.0.0"]
