version: "3"
services:
  site:
    image: threetreeslight/docker-hugo
    volumes:
      - ./blog:/site
    ports:
      - "1313:1313"
    command: ["hugo", "server", "-D", "--baseURL=http://${DOCKER_HOST_IP}:1313", "--bind=0.0.0.0"]

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
