version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: git submodule update --init
      - setup_remote_docker
      - run:
          name: build and push blog image
          command: |
            IMAGE_NAME=threetreeslight/blog
            docker build -t $IMAGE_NAME:$CIRCLE_SHA1 -t $IMAGE_NAME:latest .

            docker login -u threetreeslight -p $DOCKER_PASS
            docker push $IMAGE_NAME:$CIRCLE_SHA1
            docker push $IMAGE_NAME:latest
