global:
  slack_api_url: 

route:
  receiver: slack
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  group_by: ['cluster','alertname','instance']

receivers:
- name: slack
  slack_configs:
  - send_resolved: true
    channel: '#blog'
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
    footer: '{{ template "slack.default.footer" . }}'
    icon_url: 'https://github.com/cncf/artwork/blob/master/prometheus/icon/color/prometheus-icon-color.png?raw=true'
    pretext: '{{ template "slack.default.pretext" . }}'
    short_fields: false
    title: '{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }} {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
    text: "{{ range .Alerts }}{{ .Annotations.description }}{{ end }}"
    title_link: '{{ template "slack.default.titlelink" . }}'
    username: 'prometheus'
