global:
  slack_api_url: https://hooks.slack.com/services/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

route:
  group_by: ['alertname', 'cluster']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: slack

receivers:
- name: slack
  slack_configs:
  - send_resolved: true
    channel: '#blog'
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
    footer: '{{ template "slack.default.footer" . }}'
    icon_url: 'https://pbs.twimg.com/profile_images/588945677599780865/mrhc1gSh_400x400.png'
    pretext: '{{ template "slack.default.pretext" . }}'
    short_fields: false
    title: '{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }} {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
    text: "{{ range .Alerts }}{{ .Annotations.description }}{{ end }}"
    title_link: '{{ template "slack.default.titlelink" . }}'
    username: 'prometheus'
