groups:
- name: alert.rules
  rules:
  - alert: EndpointDown
    expr: probe_success == 0
    for: 10s
    labels:
      severity: "critical"
    annotations:
      summary: 'Endpoint {{ $labels.instance }} down'
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been has been down for more than 10 seconds.'
