apiVersion: v1
data:
  gf-security-admin-password: Jm8Tiu7oNOUnJqsju4ybCi3GzDCsrO7olMIQjve7j4YoRVzHqhNlNHdGSAt4Xrpl.U7JEgP23wHjmJ4n+.abd6h4VJeJFiBw/f3cuIZg==
kind: Secret
metadata:
  labels:
    app: monitor
  name: monitor-secret
  namespace: monitoring-system
type: Opaque
# kubesec:v:3
# kubesec:gcp:projects/threetreeslight/locations/global/keyRings/blog/cryptoKeys/monitor:CiQAsG73VrljyczI+sH55VkLzRdthkxHbKaRJuiTeyHV1BrW6fESSQDronI7FGY9U3EELxAbAw9wSkKYSfnHnmMn032Rb/wz8RE1HS0KJlCwU9+yBx6Ei0SALFRusZV0dlKteOkqqLREYdl0wTAW4hg=
# kubesec:mac:e17+Tm9U38I1cKX0.qMX5yDT+tGtBz897a0B54A==
